<?php

namespace Database\Seeders;

use App\Models\University;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UniversitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        University::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        $districts = array(
            array('id' => '1','name' => 'University of Dhaka'),
            array('id' => '2','name' => 'University of Rajshahi'),
            array('id' => '3','name' => 'University of Chittagong'),
            array('id' => '4','name' => 'Jahangirnagar University'),
            array('id' => '5','name' => 'Islamic University'),
            array('id' => '6','name' => 'Khulna University'),
            array('id' => '7','name' => 'Jagannath University'),
            array('id' => '8','name' => 'Comilla University'),
            array('id' => '9','name' => 'Jatiya Kabi Kazi Nazrul Islam University'),
            array('id' => '10','name' => 'Bangladesh University of Professionals'),
            array('id' => '11','name' => 'Begum Rokeya University'),
            array('id' => '12','name' => 'Sheikh Hasina University'),
            array('id' => '13','name' => 'Bangabandhu Sheikh Mujibur Rahman University'),

            array('id' => '14','name' => 'Bangabandhu Sheikh Mujib Medical University'),
            array('id' => '15','name' => 'Chittagong Medical University'),
            array('id' => '16','name' => 'Rajshahi Medical University'),
            array('id' => '17','name' => 'Sylhet Medical University'),
            array('id' => '18','name' => 'Sheikh Hasina Medical University-Khulna'),

            array('id' => '19','name' => 'Shahjalal University of Science and Technology'),
            array('id' => '20','name' => 'Hajee Mohammad Danesh Science & Technology University['),
            array('id' => '21','name' => 'Mawlana Bhashani Science and Technology University['),
            array('id' => '22','name' => 'Patuakhali Science and Technology University'),
            array('id' => '23','name' => 'Noakhali Science and Technology University'),
            array('id' => '24','name' => 'Jashore University of Science and Technology'),
            array('id' => '25','name' => 'Pabna University of Science and Technology'),
            array('id' => '26','name' => 'Bangabandhu Sheikh Mujibur Rahman Science and Technology University'),
            array('id' => '27','name' => 'Rangamati Science and Technology University'),
            array('id' => '28','name' => 'Bangamata Sheikh Fojilatunnesa Mujib Science & Technology University'),
            array('id' => '29','name' => 'Chandpur Science and Technology University'),
            array('id' => '30','name' => 'Sunamganj Science and Technology University'),
            array('id' => '31','name' => 'Bogura Science and Technology University'),
            array('id' => '32','name' => 'Lakshmipur Science and Technology University'),

            array('id' => '33','name' => 'Bangladesh University of Textiles'),
            array('id' => '34','name' => 'Bangabandhu Sheikh Mujibur Rahman Maritime University'),
            array('id' => '35','name' => 'Bangabandhu Sheikh Mujibur Rahman Aviation and Aerospace University'),
            array('id' => '36','name' => 'Chittagong Veterinary and Animal Sciences University'),
            array('id' => '37','name' => 'Bangabandhu Sheikh Mujibur Rahman Digital University'),

            array('id' => '38','name' => 'Bangladesh Agricultural University'),
            array('id' => '39','name' => 'Bangabandhu Sheikh Mujibur Rahman Agricultural University'),
            array('id' => '40','name' => 'Sher-E-Bangla Agricultural University'),
            array('id' => '41','name' => 'Khulna Agricultural University'),
            array('id' => '42','name' => 'Habiganj Agricultural University'),
            array('id' => '43','name' => 'Kurigram Agricultural University'),

            array('id' => '44','name' => 'Bangladesh University of Engineering & Technology'),
            array('id' => '45','name' => 'Khulna University of Engineering & Technology'),
            array('id' => '46','name' => 'Chittagong University of Engineering & Technology'),
            array('id' => '47','name' => 'Rajshahi University of Engineering & Technology'),
            array('id' => '48','name' => 'Dhaka University of Engineering & Technology'),

            array('id' => '49','name' => 'Open University of Bangladesh'),
            array('id' => '50','name' => 'Sylhet Agricultural University'),
            array('id' => '51','name' => 'National University of Bangladesh'),
            array('id' => '52','name' => 'Islamic Arabic University'),

            array('id' => '53','name' => 'International University of Business Agriculture and Technology'),
            array('id' => '54','name' => 'North South University'),
            array('id' => '55','name' => 'University of Science & Technology Chittagong'),
            array('id' => '56','name' => 'Central Womens University'),
            array('id' => '57','name' => 'Independent University, Bangladesh'),
            array('id' => '58','name' => 'American International University-Bangladesh'),
            array('id' => '59','name' => 'Ahsanullah University of Science and Technology'),
            array('id' => '60','name' => 'Dhaka International University'),
            array('id' => '61','name' => 'International Islamic University, Chittagong'),
            array('id' => '62','name' => 'Asian University of Bangladesh'),
            array('id' => '63','name' => 'East West University'),
            array('id' => '64','name' => 'Gono Bishwabidyalay'),
            array('id' => '65','name' => 'Peoples University of Bangladesh'),
            array('id' => '66','name' => 'Queens University'),
            array('id' => '67','name' => 'University of Asia Pacific (Bangladesh)'),
            array('id' => '68','name' => 'BGMEA University of Fashion & Technology'),
            array('id' => '69','name' => 'Chittagong Independent University (CIU)'),
            array('id' => '70','name' => 'Bangladesh University'),
            array('id' => '71','name' => 'BGC Trust University Bangladesh'),
            array('id' => '72','name' => 'BRAC University'),
            array('id' => '73','name' => 'Manarat International University'),
            array('id' => '74','name' => 'Premier University, Chittagong'),
            array('id' => '75','name' => 'Pundra University of Science and Technology'),
            array('id' => '76','name' => 'Southern University, Bangladesh'),
            array('id' => '77','name' => 'Sylhet International University'),
            array('id' => '78','name' => 'City University, Bangladesh'),
            array('id' => '79','name' => 'Daffodil International University'),
            array('id' => '80','name' => 'Green University of Bangladesh'),
            array('id' => '81','name' => 'IBAIS University'),
            array('id' => '82','name' => 'Leading University'),
            array('id' => '83','name' => 'Northern University, Bangladesh'),
            array('id' => '84','name' => 'Northern University of Business and Technology Khulna'),
            array('id' => '85','name' => 'Prime University'),
            array('id' => '86','name' => 'Southeast University'),
            array('id' => '87','name' => 'Prime University'),
            array('id' => '88','name' => 'Stamford University Bangladesh'),
            array('id' => '89','name' => 'State University of Bangladesh'),
            array('id' => '90','name' => 'University of Development Alternative'),
            array('id' => '91','name' => 'Bangladesh University of Business and Technology'),
            array('id' => '92','name' => 'Eastern University, Bangladesh'),
            array('id' => '93','name' => 'Metropolitan University'),
            array('id' => '94','name' => 'Millennium University'),
            array('id' => '95','name' => 'Presidency University'),
            array('id' => '96','name' => 'Primeasia University'),
            array('id' => '97','name' => 'Royal University of Dhaka'),
            array('id' => '98','name' => 'Shanto-Mariam University of Creative Technology'),
            array('id' => '99','name' => 'United International University'),
            array('id' => '100','name' => 'University of Information Technology and Sciences'),
            array('id' => '101','name' => 'Uttara University'),
            array('id' => '102','name' => 'University of South Asia, Bangladesh'),
            array('id' => '103','name' => 'Victoria University of Bangladesh'),
            array('id' => '104','name' => 'World University of Bangladesh'),
            array('id' => '105','name' => 'Atish Dipankar University of Science and Technology'),
            array('id' => '106','name' => 'Asa University Bangladesh'),
            array('id' => '107','name' => 'University of Liberal Arts Bangladesh'),
            array('id' => '108','name' => 'Bangladesh Islami University'),
            array('id' => '109','name' => 'East Delta University'),
            array('id' => '110','name' => 'Britannia University'),
            array('id' => '112','name' => 'Feni University'),
            array('id' => '113','name' => 'Khwaja Yunus Ali University'),
            array('id' => '114','name' => 'Bangladesh University of Health Sciences'),
            array('id' => '115','name' => 'European University of Bangladesh'),
            array('id' => '116','name' => 'First Capital University Of Bangladesh'),
            array('id' => '117','name' => 'Hamdard University Bangladesh'),
            array('id' => '118','name' => 'Ishakha International University'),
            array('id' => '119','name' => 'North East University Bangladesh'),
            array('id' => '120','name' => 'North Western University, Bangladesh'),
            array('id' => '121','name' => 'Port City International University'),
            array('id' => '122','name' => 'Sonargaon University'),
            array('id' => '123','name' => 'Varendra University'),
            array('id' => '124','name' => 'ZH Sikder University of Science & Technology'),
            array('id' => '125','name' => 'Rajshahi Science & Technology University'),
            array('id' => '126','name' => 'Coxs Bazar International University'),
            array('id' => '127','name' => 'Exim Bank Agricultural University Bangladesh'),
            array('id' => '128','name' => 'Fareast International University'),
            array('id' => '129','name' => 'German University Bangladesh'),
            array('id' => '130','name' => 'North Bengal International University'),
            array('id' => '131','name' => 'Notre Dame University Bangladesh'),
            array('id' => '132','name' => 'Ranada Prasad Shaha University'),
            array('id' => '133','name' => 'Sheikh Fazilatunnesa Mujib University'),
            array('id' => '134','name' => 'Times University Bangladesh'),
            array('id' => '135','name' => 'Bangladesh Army International University of Science & Technology'),
            array('id' => '136','name' => 'Bangladesh Army University of Engineering & Technology'),
            array('id' => '137','name' => 'Canadian University of Bangladesh'),
            array('id' => '138','name' => 'CCN University of Science & Technology'),
            array('id' => '139','name' => 'Global University Bangladesh'),
            array('id' => '140','name' => 'NPI University of Bangladesh'),
            array('id' => '141','name' => 'Rabindra Maitree University'),

            array('id' => '142','name' => 'The International University of Scholars'),
            array('id' => '143','name' => 'University of Creative Technology Chittagong'),
            array('id' => '144','name' => 'Anwer Khan Modern University'),
            array('id' => '145','name' => 'Central University of Science and Technology'),
            array('id' => '146','name' => 'Tagore University of Creative Arts'),
            array('id' => '147','name' => 'University of Global Village'),
            array('id' => '148','name' => 'Bandarban University'),
            array('id' => '149','name' => 'Trust University, Barishal'),
            array('id' => '150','name' => 'University of Brahmanbaria'),
            array('id' => '151','name' => 'University of Skill Enrichment and Technology'),
            array('id' => '152','name' => 'International Standard University'),
            array('id' => '153','name' => 'ZNRF University of Management Sciences'),
            array('id' => '154','name' => 'RTM Al-Kabir Technical University'),
            array('id' => '156','name' => 'Islamic University of Technology'),
            array('id' => '157','name' => 'Asian University for Women'),
        );

        DB::table('universities')->insert($districts);
    }
}
